### ISSUE TITLE
Joypad input not working from API call? 

### ISSUE THREAD

**Issue by brummetj** [lukexor/tetanes#167]
Hi there! 

I'm doing something crazy.. and that's taking your emulator and trying to run it as a background process and stream the pixels out via webRTC by packaging them into a vp8 encoder. 

It turns out pretty successful ill be honest, the clocking frame + frame buffer + packaged vp8 frame. 

But it seems when i trigger the `joypad.set_button()`, the next frame doesn't seem to present anything. 

Any ideas by chance?

**Comment by lukexor** [comment]
That's pretty interesting!

Without seeing more of your code I'm not really sure - but depending on the game and how often it polls for key presses, it might just not be set long enough. Most games should be reading at least once a frame, but some games read multiple times, especially if they support fourscore. It could be that the specific game you're testing requires a press followed by a release but I'd need more detail.

You can read more about controller reads here: https://www.nesdev.org/wiki/Controller_reading

TetaNES currently doesn't emulate any DPCM conflicts or anything either so internally it's either pressed or not and it's up to the game to read the port state.

There's a debugger feature you could try to use (depending which version of TetaNES you're using, I think on main it might need some fixing) to drill down into the per-CPU instruction state of the emulator.

**Comment by brummetj** [comment]
thanks for the info and quick response! I'm just using the `main` is there a different branch that you suggest? 

here is what I'm doing for the main loop

```
            match self.data_channel_rx.try_recv() {
                Ok(msg) => {
                    if let Ok(event) = ButtonEvent::from_str(msg.as_str()) {
                        let success = self.emulator.handle_joypad_pressed(Slot::One, event.clone(), true);
                        log::info!("pressed on frame number: {:?}", self.emulator.control_deck.frame_number());
                        if !success {
                            log::error!("failed to register event input");
                        }
                        log::info!("handled event successfully {msg}");
                    }
                }
                Err(mpsc::error::TryRecvError::Empty) => {} // handle no messages
                Err(e) => {
                    return log::error!("error in controls channel: {e}");
                }
            }

            self.emulator.clock_frame();

            let width = self.emulator.width();
            let height = self.emulator.height();
            let now = Instant::now();
            let mut frame = self.emulator.frame();
            let time =  now - self.start_time;

            let ms = time.as_secs() * 1000 + time.subsec_millis() as u64;

            let mut f = converter::yuv::rgba_to_yuv(&mut frame, width, height, 4);
            for frame in self.encoder.vpx.encode(ms as i64,&mut f).unwrap() {
                self.sample.data = Bytes::copy_from_slice(frame.data);
                self.sample.duration = time;
                self.sample.packet_timestamp = frame.pts as u32;
                if let Err(e) = self.sampler_track.write_sample(&self.sample).await {
                    log::debug!("failed to send packet: {e}");
                }
            }
            time::sleep(time::Duration::new(0,10000)).await;
            self.start_time = now;
```

where the `handle_joypad_pressed` is just calling `joypad.set_button` from the joypad_mut. i just have `pressed == true`. would I need to follow up with a `false` to have it released? 

I'm using the game called `Excitebike.nes` to test.  I do see the game load and run fine with the PixelEngine library you use as well with the wasm web build. Although the audio is a little funky there i'm sure you are aware of.

**Comment by lukexor** [comment]
So yeah I'm guessing you need to accept both press and release events from your channel and set true/false appropriately. Have you tried that yet?

The `bool` that's returned from `handle_joypad_pressed` isn't a success value - it's a "this event was handled value" and is used by pix-engine to avoid propagating any further event handling. i.e. returning "true" means stop processing event handlers for this event. It doesn't matter much in this context, but it has more impact if there are certain key mappings that might be used by pix-engine for UI interactions (like ctrl-c for copy for example)

Yeah the audio with WASM is sub-par, especially on a slow network or lower end machine and I haven't had the time to figure out how to use the web audio APIs better to sort it out, given the real-time nature of the emulation.

SDL2 specifically advises against running on anything other than the main thread: https://rust-sdl2.github.io/rust-sdl2/sdl2/struct.Sdl.html

If you need multiple threads I'd advise either moving something other than SDL to other threads, or using a single-threaded executor like tokio offers which allows you to share the thread more efficiently.

**Comment by brummetj** [comment]
I have hard coded a set true/false to simulate a button press and release but am still unable to get any results with the frame updating. 

Thanks for the info!

**Comment by brummetj** [comment]
it turns out I needed to run the clock frame after each key-down press... thanks @lukexor for the help!

**Comment by lukexor** [comment]
ah! yeah! CPU has to run to parse the controller inputs. Glad you figured it out!
