### ISSUE TITLE
404 Not Found on Web compilation option from Readme

### ISSUE THREAD

**Issue by Vali5681** [lukexor/tetanes#171]
Apparently, the option showed in Readme about the possibilit of compiling on the web, does not work anymore. It shows the following message:
![image](https://github.com/lukexor/tetanes/assets/6222937/50de7b13-bdd3-4120-b5e4-5c43b42febe8)

What can be done in this endeavour?

P.S.: As a side note, I'd be interested to join on part of either improving the code coverage, or the mapping, in order to improve the number of games which can run on this emulator. As a first question, what are the challenges you are facing on either mapping part or improving code coverage? In my opinion, I could be of more use on improving the code coverage part.

**Comment by lukexor** [comment]
If that's for the TetaNES browser link, I've fixed it.

As for contributing, any PRs are welcome! For mappers it's simply a matter of referring to the NES wiki and creating a module for a missing mapper, adding the logic similar to existing mappers and updating the enum/load mapper method.

For code coverage, a lot of the internals could use more rigorous unit tests specially around some of the more esoteric NES features/bugs that are being emulated
