### ISSUE TITLE
Pal audio stream not downsampled correctly

### ISSUE THREAD

**Issue by tedsteen** [lukexor/tetanes#218]
When running pal the audio sample rate seems to be a bit too low. Ntsc is correct afaik, Dendy I haven't tried.

Note I am using the engine rework branch

**Comment by lukexor** [comment]
Do you happen to know any more details? The audio sample rate is set to 44.1khz and the only thing that affects the audio when switching regions is the clock rate - as the APU in PAL clocks at 50hz instead of 60hz and has a different frame counter. So in general audio sounds slower on PAL than NTSC.

I can't see anything specifically wrong with it comparing to Mesen and playing a PAL game like Aladdin and manually switching between PAL and NTSC you can notice the speed change, where the slower PAL speed sounds more accurate.

If you have a specific game or sampling rate expectation for comparison let me know.

**Comment by tedsteen** [comment]
Sorry, I just pulled down the latest changes and adapted to the new api and now it works as expected!
I didn't take the clock rate into account when changing the sample rate. Now I do and it sounds correct.

Still the tetanes native emulator in the `engine-rework`-branch is suffering from the problem.

**Comment by lukexor** [comment]
Hm. Glad to see you got it working.

I specifically removed setting a custom sample rate for now unless it's a higher requested feature - The idea being that the APU runs at a native 1.79Mhz (NTSC) or 1.66Mhz (PAL) and ultimately it doesn't matter what your sound card sample rate is as most modern sound cards support 44.1khz and there's little to be gained in quality to changing it. Higher sample rates just cost more CPU.

Internally the APU downsamples to an intermediate sample rate 88200 (2x 44.1khz) for filtering - and then the APU sample period is set to decimate that down to 44.1khz by taking ~every other sample based on the CPUs clock rate. The clock rate is the only source of real "wall time" the APU has access to, so the end sampling rate for both NTSC and PAL should still be ~44.1khz even though the sampling period is different.

I do see the bug there though - The APU set_region method is forgetting to change the apu.sample_period based on the changed clock rate so thanks!

Do you have a strong need for a different output sampling rate other than 44.1khz?

**Comment by tedsteen** [comment]
So my use case is a bit involved..

I set the nes sample rate to be the same as the audio interface (probably always 44100). I then push audio to a bounded blocking queue with a small length which is being consumed by the audio device thread. Essentially driving the emulator using the audio clock.

If netplay is active there might be situation where we need to run the emulator a tiny bit slower to let clients catch up. I do this by altering the sample rate.

**Comment by tedsteen** [comment]
> I see. Doesn't that result in noticable pitch shifting? I wonder with a high enough audio latency you'd have room to clock more or less and still not underrun audio while keeping the sample rate constant.

When I'm one frame ahead I slow down very little, when two I do a bit more etc. Most of the time clients are in sync, but there is a drift, and sometimes there are hickups and things get out of sync.

> 
> Generally modifying the output sampling rate would mean interpolating or decimating the samples, which wouldn't change the clock rate so doing it this way would seemingly affect the pitch.
Yes, it does effect the pitch
> 
> I previously explored dynamic rate control but had trouble getting it working correctly. I may need to revisit it.
> 
> https://bsnes.org/articles/dynamic-rate-control/#:~:text=When%20running%20a%20native%20game,result%20is%20a%20seamless%20experience.

That would basically do the same no? they also stretch the sound (which effect the pitch) I just do by changing the sample rate and since you already do the downsampling I get two birds in one stone!

You should ofc keep the API the way you want it, if the intention is that 44100 is the default sample rate then it makes total sense.

I would be happy if you kept the back door open tho so I can access the `apu.filter_chain` and `apu.sample_period` :)

**Comment by lukexor** [comment]
Yeah dynamic rate control does change the pitch but it's usually kept low enough with a min/max that it's not noticeable.

Okay. Yeah the fields will remain public, primarily to allow other developers and TetaNES itself to add debugging features in the future that may need to inspect or modify the internals separately from the standard API for intended behavior

**Comment by tedsteen** [comment]
Hey, I just wanted to let you know that I plan to merge this one soonish:
https://github.com/tedsteen/nes-bundler/pull/109 (today or tomorrow) and
then perhaps do a release.
It contains a switch over to tetanes in favour of rusticnes-core.
I know I am on an active refactoring branch of yours but I like the fact
that the core is extracted and I can depend on it as a single crate. I
don't persist any state from the nes except the sram.

At least I made a fork with my own branch so I can slowly pull in your
changes as they come.
I hope I'm not stressing you out too much by doing this :)



Den lör 30 mars 2024 kl 19:41 skrev Luke ***@***.***>:

**Comment by lukexor** [comment]
That's great! Happy you're making good use of the core. No stress for me,
I'm trying to wrap up a few features before doing a release also and the
core isn't likely to change much but will also get a separate crates
version published as well.

After that I'd like to plan for a stabilizing release of core so there may
be some breaking changes until then. If you have any thoughts on preferred
API changes lmk!


- L
