### ISSUE TITLE
Audio issues

### ISSUE THREAD

**Issue by tedsteen** [lukexor/tetanes#219]
There is something off with the audio, it is hard to pinpoint what it could be, but I have noticed it a few times and today it was very prominent when I was trying a homebrew called "Pye the Pyper".  You can download it here: https://retronii.itch.io/pye-the-pyper

The music in that game is not playing correctly with tetanes.

I wish I had more specifics but I don't know enough about the internals to know what might be going wrong.

I have also noticed that the noise sometimes play wrong, f.ex when playing Super Mario Bros. 1 the hi-hat sound randomly starts playing in a strange more prolonged way.

**Comment by lukexor** [comment]
Okay I'll give it a look. There's an audio recording feature too if you happen to capture specific cases. Right now it's just a raw format (wave is planned for later) but can be loaded into audacity for comparison

**Comment by lukexor** [comment]
I think I've narrowed it one issue down to the pulse channels on PAL. It seems to be the wrong pitch. Have you noticed any pulse issues with NTSC games?

I can't pinpoint the noise channel issue - which level did you encounter it?

**Comment by lukexor** [comment]
I just pushed up some changes to the length counter, envelope and sweeps and they sound pretty good on the examples given. Lmk if there are still noticeable issues!

**Comment by tedsteen** [comment]
Pye the pyper sounds much better!
But SMB 1 is now in a worse state I'm affraid.

**Comment by tedsteen** [comment]
Pye the pyper sounds much better!
But SMB 1 is now in a worse state I'm afraid.
https://www.emulatorgames.net/roms/nintendo/super-mario-bros/

The most noticeable defects are
* The jump sound
* When mario gets hit by an enemy
* When sliding down the flag at level end
* The sound of the explosions after you finish the level

It's something with one or both the squares. It could be related to sliding notes somehow, because it sounds to me that when the pitch is supposed to change it doesn't. 
The download I provided is a PAL game. The defects are showing up in both PAL and NTSC.

The hi-hat is still doing the weird thing in SMB1

**Comment by lukexor** [comment]
Thanks for the details! Looks like I have my work cut out for me! 😁

**Comment by tedsteen** [comment]
Since the last commits I can't really hear any audio issues any more!
