### ISSUE TITLE
Volume is lower on Ntsc compared to Pal

### ISSUE THREAD

**Issue by tedsteen** [lukexor/tetanes#223]
What the title says :)

**Comment by lukexor** [comment]
Doh. I read https://www.nesdev.org/wiki/APU_Mixer as ntsc having 3 filters and pal having only the 1 and I saw rusticnes doing it similarly but it is specifically talking the famicon vs NES. Nothing about Pal id mentioned. Famicon was always ntsc, but just had a different DAC and RF output among other hardware differences.

So this is a bug, audio filtering shouldn't depend on region and I haven't done any work to emulate famicon specifically. Thanks for reporting!
