### ISSUE TITLE
Not able to access private dependency

### ISSUE THREAD

**Issue by tedsteen** [lukexor/tetanes#246]
When depending on tetanes-core through git the build fails because of afaic a dependency on homebrew-formulae

https://github.com/tedsteen/nes-bundler/actions/runs/9192922817

**Comment by lukexor** [comment]
doh! silly of me. let me fix that.

**Comment by tedsteen** [comment]
Perhaps a tetanes-core repository? 😇

**Comment by lukexor** [comment]
main should be fixed now.

**Comment by tedsteen** [comment]
> main should be fixed now.

works! :)
