### ISSUE TITLE
Add Famicom 4-Player support

### ISSUE THREAD

**Issue by mantou132** [lukexor/tetanes#78]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

game: Nekketsu Fighting Legend

```rs
log(&format!("{:?}", self.control_deck.gamepad_mut(GamepadSlot::Three)));
```

```
[Log] Gamepad { left: false, right: false, up: false, down: false, a: true, b: false, turbo_a: false, turbo_b: false, select: false, start: false, strobe: 0 }
[Log] Gamepad { left: false, right: false, up: false, down: false, a: false, b: false, turbo_a: false, turbo_b: false, select: false, start: false, strobe: 0 }
```

**Comment by lukexor** [comment]
Did you try enabling the fourscore option on the console? By default only 2 gampads are read from input.

**Comment by lukexor** [comment]
Okay I'll take a look. I had gotten 4 player working by testing Gauntlet II, but haven't gotten controller detection for 4 players set up yet so haven't fully been able to test regularly so it may have stopped working recently

**Comment by lukexor** [comment]
It does thanks! Yeah currently only the fourscore format is supported for Players 3 and 4. I'll look into adding support for the famicom format as well.

**Comment by mantou132** [comment]
@lukexor 

My previous test was incomplete.

In fact, when I use p3, p1 will also be manipulated

**Comment by mantou132** [comment]
@lukexor  

Today I tried the latest code from the main branch and the problem reappeared.

![Screenshot 2023-03-30 22 20 42](https://user-images.githubusercontent.com/3841872/228868273-87ff6a4a-4dd5-4ae8-8360-8e3902c3c97b.png)

download:
https://github.com/mantou132/nesbox/files/9043747/nes.zip

**Comment by lukexor** [comment]
Finally got some time to look at this. Recently I did split out Fourscore and Satellite as two separate options. If you go into the Config menu (Ctrl-C, or Escape and click Config), then select Satellite for Four Player Mode it should work as expected. See the attached screenshot.

![Screen Shot 2023-04-15 at 12 45 19 PM 1](https://user-images.githubusercontent.com/709609/232250363-f64c6003-8101-4a2b-bd14-5e43691d20f2.png)
